### ISSUE TITLE
Need Good Articles to be written in format

### ISSUE THREAD

**Issue by bhargav-joshi** [bhargav-joshi/LearnFree#70]
### Format  
1. Take a Reference of [This File](https://github.com/bhargav-joshi/LearnFree/blob/main/Learn-git.html)
2. Visit it once - [Click Here](https://bhargav-joshi.github.io/LearnFree/Learn-git.html)
3. You have to make articles in this format or layout
4. Just add the content and change the title and do the required changes
5. After confirming all save it with **ArticleName.html**
6. Make a Pull Request with the proper title

**Comment by imbhavesh28** [comment]
Thank's, Bhargav!
I found couple of issues in this website, I will change & make PR for the same.
